### ISSUE TITLE
Calli:Bot Auswahl mit Port B

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/openroberta-lab#102]
**Describe the bug**
 - Es scheint nicht möglich zu sein, im Motor-Block Port B auf calliBot zu stellen.

**To Reproduce**
1. Go to 'or lab'
2. Click on Calliope
3. Scroll down to 'Aktion, Motor Block
4. See error, when try to select calliBot rechts at Port B

**Expected behavior**
 - CalliBot rechts lässt sich auswählen

**Screenshots**
 
![Screenshot_20190619-151858](https://user-images.githubusercontent.com/19221359/59769273-153c2380-92a6-11e9-8b6b-01c417ab41b4.jpg)

**Device information**
 - Type [Desktop/tablet/smartphone]
 - OS: [e.g. windows], including version
 - Browser [e.g. chrome, firefox], including version

**Additional context**
 - Add any other context about the problem here.

**Comment by bjost2s** [comment]
No, it is not possible, because Calli:Bot has a fixed base without port A and B. Calli:Bot has a right and left motor with fixed ports as available in the block. Please check the documentation once it is available.
Or have a look on the configuration of Calliope, there you can see where Port A and B are located.
![image](https://user-images.githubusercontent.com/1613069/59804277-26a91e00-92ee-11e9-83fb-2e8a74397b77.png)

**Comment by VinArt** [comment]
I think the issue here is in that there should be symmetry in the way one chooses the callibot motors, so it would not matter from which port the change is made, in any case both should be changed to callibot motors.

**Comment by Thorlogy** [comment]
Any progress?

**Comment by boonto** [comment]
Works now.
