### ISSUE TITLE
generated C++ program for sensebox is wrong, casting problem

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/openroberta-lab#1040]
(at least for sensebox) a program, that tries to convert arrays/lists to strings, generates an invalid cast. The compiler complains.

This occurs, for instance, if you try to output a list of numbers to the OLED I2C display: the list is connected to the show test plug, which expects a string. This generates the wrong cast.

This s a rare error because usually only primitive types are written to the display.

**Comment by RaghuvirShirodkar** [comment]
This problem is also encountered with Arduino robots, in essence with robots that use library Adafruit_SSD1306.
There is no matching function signature with std::list for print functions in the lib. 

An idea would be to iterate through the input list in the generated code and then call the relevant print function in the library. This way, only primitive data types are being used as inputs when calling the function.
