### ISSUE TITLE
EV3dev steering backwards does not move the robot backwards

### ISSUE THREAD

**Issue by Ch40sl0rd** [OpenRoberta/openroberta-lab#1109]
when using the "steer backwards" block, either with or without specifying a distance to drive, the physical robot moves forwards. Only when using a negative distance does the robot actually drive backwards.

**Comment by Ch40sl0rd** [comment]
@ensonic could you please take a look at this, I assume the problem lies in the method DriveInCurve in ev3.py

**Comment by PamoCurtis** [comment]
Is this issue still existing? Because i can't reproduce it on **lab.open-roberta.org** nor **test.open-roberta.org**

**Comment by bjost2s** [comment]
please test this again and share the results

**Comment by RaghuvirShirodkar** [comment]
It seems that the latest EV3dev package ([release 1.7.4](https://github.com/OpenRoberta/robertalab-ev3dev/releases/tag/v1.7.4)) has a typo in `driveInCurve()` method, as can be [seen here](https://github.com/OpenRoberta/robertalab-ev3dev/blob/9100fae26830e2b0230fa81d10053854d1951406/roberta/ev3.py#L520).

As a result, the robot never `steers` backward, because the code expects parameter backward***s***!

Furthermore, it seems release 1.7.4 (dated 19.01.2018) is [missing commits](https://github.com/OpenRoberta/robertalab-ev3dev/compare/v1.7.4...develop) made to `develop` since the release. A quick look at the commits shows that the corrections are already in `develop`, so perhaps a new version of the package needs to be released?
