### ISSUE TITLE
Facing an issue to design my own robot implementation

### ISSUE THREAD

**Issue by KondraDivya** [OpenRoberta/openroberta-lab#1126]
I am trying to clone the current mBot implementation to design my own robot implementaion and facing difficulty in modifying web/html files because I couldn't find the source code in my repository.Hope you will help me with this.

![Screenshot (381)](https://user-images.githubusercontent.com/88012589/136590445-93209acd-a521-4f73-ad5e-9134b852a8a1.png)

**Comment by bjost2s** [comment]
Robot related properties, like visual names, capabilities etc are defined server side in the properties. For mBot you can find the properties [here](https://github.com/OpenRoberta/openroberta-lab/blob/develop/RobotArdu/src/main/resources/mbot.properties). You can change the robot.real.name, if you want. Simply rebuild the system, restart the server and you should see the changes on the website. 
All robot related properties are stored in projects together with the source code. For Arduino like systems we have one project, RobotArdu, so that all Arduino like systems can reuse code easily.
