### ISSUE TITLE
Cannot reset my password anymore - server does not send mails

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#1164]
When I try to reset my passwort and type in the correct email I got the following message
![image](https://user-images.githubusercontent.com/1613069/144974658-8aee210f-9c71-460e-8ead-187619a3f2de.png)
and no mail

**Comment by rbudde** [comment]
On sunday we updated/upgraded the ubuntu-18.04 of out prod machine. Now it has the same level as our test machine. This may be the cause of the problem.

But: Mail to internal and external adresses works fine with the test server.

**Comment by rbudde** [comment]
The upgrade of Ubuntu lead to a restriction in name resolution. The name of the postfix server `me-roblab-prod` could nor be resolved anymore. Changes in the start parameters of the server are needed: Instead of `me-roblab-prod` the ip address of the gateway of the docker network `ora-net` (that is `172.20.0.1` on the prod machine) has to be used

**Comment by bjost2s** [comment]
fixed with changed mail properties
