### ISSUE TITLE
Program Export does not work

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/openroberta-lab#1279]
With Safari on MacBook MOS Monterey Version12.3.1 the export of a program does not work

**Comment by joernalraun** [comment]
This is the same on any MacOS when using Safari.

**Comment by bjost2s** [comment]
What exactly happens? What are the error messages if any, or do you see something in the log?

**Comment by Thorlogy** [comment]
Nothing happens, no error messages nothing. 

Log: 
<img width="1531" alt="image" src="https://user-images.githubusercontent.com/19221359/165103496-4f4092cc-2ee0-41db-a4ae-032a4c40a1a7.png">

**Comment by RaghuvirShirodkar** [comment]
Program export (and import) works on the MacBook that I have here...

## Tested on:
MacOS Monterey v12.1

## Browsers:
Safari v15.2
Firefox v91.5.0esr

Tested on `lab` as well as `test`.

**Comment by joernalraun** [comment]
@RaghuvirShirodkar This has been an issue since a couple of years, but only on Safari...

**Comment by RaghuvirShirodkar** [comment]
I think I found the bug that causes this issue and how to reproduce it.

## Probable cause
`download` attribute for `a` tag doesn't seem to work for some newer Safari versions.

## Steps to reproduce
1. Go to `lab.open-roberta.org`.
2. Create a sample program for any robot.
3. Click on the _edit_ menu -> _export program_.
4. Observe that nothing is downloaded.

Since I was exporting the program through keyboard shortcuts (Ctrl + E), it was working for me. However, when I try to export the program through the menu, nothing is downloaded.

**Comment by Thorlogy** [comment]
Program Export with Safari works now
