### ISSUE TITLE
Ternary If: wrong code is executed in sim when nested in

### ISSUE THREAD

**Issue by PamoCurtis** [OpenRoberta/openroberta-lab#1291]
**Describe the bug**
Executing the example code in the sim will execute both times the false-statement in the first '**ternary if**'-block and then the true-statement in the nested in '**ternary if**'-block even though the first '**ternary if**'-block is already set to true

![Screenshot from 2022-05-04 12-57-07](https://user-images.githubusercontent.com/59732238/166670008-4cade209-b402-4e10-af1a-ca80cb12ee1e.png)

**Example Program**
[ternary_if_bug.xml.txt](https://github.com/OpenRoberta/openroberta-lab/files/8619539/ternary_if_bug.xml.txt)

**Comment by rbudde** [comment]
this is an old error, reproducable on the prod system. The problem is the recursive use of `if/ternary if` structures. The generated code is definitively wrong. The following program has the same problem:
[if_ternary_if_bug.xml.txt](https://github.com/OpenRoberta/openroberta-lab/files/8621390/if_ternary_if_bug.xml.txt)

Reason of the problem: the code generator uses a functional pattern to delay the allocation of forward jump locations (because the location is only known after all sub-components have generated code). The jump location is generated too short and executes parts of the code, that should be unused.

**Comment by rbudde** [comment]
BTW: Great to find THIS error by writing a test program!

**Comment by rbudde** [comment]
seems to be close related to https://github.com/OpenRoberta/openroberta-lab/issues/1340
