### ISSUE TITLE
dark light - calliope mini

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/openroberta-lab#1369]
**Describe the bug**
 - The dark led light will not be displayed (simulation is fine)
 - 
**To Reproduce**
1. Go to 'calliope mini'
2. Click on block "turn led light on color" black
3. Download to calliope mini

**Expected behavior**
 - LED is black

**Screenshots**
 - If applicable, add screenshots to help explain your problem.

**Device information**
 - Type desktop
 - OS: windows
 - Browser chrome

**Additional context**
 - Add any other context about the problem here.

**Comment by RaghuvirShirodkar** [comment]
Black colour in RGB LEDs generally means that the three streams R + G + B = 0, so the LED remaining switched off _does indeed represent_  the colour black.

That being said, I suppose the simulation shows black simply because without it, it would appear as if the program did not run.

@bjost2s, @rbudde do you think we should consider this a simulation _error_ and correct it to maintain uniformity between the actual board and simulation?

**Comment by bjost2s** [comment]
There are many more colors that a RGB LED cannot show:
![image](https://user-images.githubusercontent.com/1613069/195510614-a4810ff4-fbe0-430f-a5f8-4265e8806248.png)
["You can only make whatever color that is in the color wheel"](https://westsideelectronics.com/you-cant-make-brown-or-black-an-rgb-led-2/),
so brown and ather dark colors are also impossible. I think the simulation is fine, because we got the RGB value there and it can be displayed on a screen.

**Comment by Thorlogy** [comment]
There should be a note within the Lab, that some colors can not be displayed on the Calliope mini. (The same hint/note will be shown sometimes when blocks can not be processed / used within the simulation.)

**Comment by bjost2s** [comment]
We could make a remark in the block description, nothing else makes sense

**Comment by Thorlogy** [comment]
<img width="501" alt="image" src="https://user-images.githubusercontent.com/19221359/195592845-1646cc08-f36a-4f49-ac3e-520cb948f49c.png">


I guess the same should be possible for real robots

**Comment by rbudde** [comment]
No, @bjost2s is right. The text shown in @Thorlogy 's example is generated at _compile time_ and states, that the block can never be used. It makes no sense to add a permanent note "some colors cannot be displayed", as you don't know at compile time, what colors are displayed. See the snippet atached. You can make it as complex as you want. BTW: the original claim, that black is not displayed on the real robot, is misleading. As @RaghuvirShirodkar noted, black means, that no color is shown on the LED.

A remark in the block description would be fine.

![2022-10-14 12_52_22-Open Roberta Lab](https://user-images.githubusercontent.com/15834363/195830246-fe6b1075-4832-4410-8ce5-2d77dd8a1ddd.jpg)
