### ISSUE TITLE
Strange behaviour SIM - changing Motor blocks within Robotconfiguration

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/openroberta-lab#1507]
**Describe the bug**
 - Changing the Motor blocks in the Robotconfiguration from B->A and C->B  
 - If only motor B is programmed, the robot moves forward. Instead of driving a curve.

**To Reproduce**
1. Go to 'OR Lab'
2. Click on 'OR SIM'
3. Configurate the Robot and code the program shown in the screenshot

**Expected behavior**
 - The robot drives a curve

**Screenshots**
<img width="372" alt="image" src="https://github.com/OpenRoberta/openroberta-lab/assets/19221359/fc8ed354-fb83-400b-ad31-57c91d3dd046">

<img width="267" alt="image" src="https://github.com/OpenRoberta/openroberta-lab/assets/19221359/4cbb4dcb-032e-4658-ae57-7d45e47f7955">

**Device information**
 - Type laptop
 - OS: mac
 - Browser chrome

**Comment by rbudde** [comment]
The reason is probably, that the simulation does not take into account, that a motor is removed from a port (say B). Even, if a new motor is connected to B. Consequently both motors start to work. This error happens if the first motor is completely REMOVED, too.

There seem to be more errors: remove the B motor, then the C motor, add a new B motor. Then the block "motor on for duration" doesn't stop anymore (ignores the duration expression)

**Comment by bjost2s** [comment]
same as [#1657](https://github.com/OpenRoberta/openroberta-lab/issues/1657)
