### ISSUE TITLE
OR SIM does not open 

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/openroberta-lab#1629]
**Describe the bug**
-The SIM-Windows window does not open when function is deactivated

**To Reproduce**
1. Go to 'OR Lab'
2. Click on 'use a function and deactivate the function'
3. Try to open the SIM Window

**Expected behavior**
 - The sim window should be open

**Screenshots**
<img width="403" alt="image" src="https://github.com/OpenRoberta/openroberta-lab/assets/19221359/c41bfdef-6b99-42f1-9603-6ba5d87f3523">

**Device information**
 - Type Laptop
 - OS: MacOS 
 - Browser Chrome

**Comment by rbudde** [comment]
the source code view opens, but the generated code is wrong. There must be a checker activated (a classical typechecker would be a good candidate), which detects, that the called functions is not defined.

This error will occur almost never, as user use the deactivate of blockly very seldom. It's likely, that this error exists since the first version of the lab has been deployed :-)
