### ISSUE TITLE
Calliope mini - Tab robot configuration CALLIOPEbasis loses name 

### ISSUE THREAD

**Issue by AHberta** [OpenRoberta/openroberta-lab#1640]
**Describe the bug**
 - After adding Calli:bot, the tab loses the name "CALLIOPEbasis".

**To Reproduce**
1. Add Calli:bot to configuration
2. See error

**Screencast**
https://github.com/OpenRoberta/openroberta-lab/assets/19265064/2ff554c2-bfd9-4174-8a6c-67f81ccf5c9d

**Device information**
 - Type: Desktop
 - OS: Windows 10
 - Browser: Chrome

**Comment by bjost2s** [comment]
@AHberta this is intended (since a long time), because with the new callibot block the configuration is not the basic/default one anymore, but an unnamed one. This unnamed one will be stored automaticly with the program (when saving or exporting it) or you can give it a name by saving it especially.
Please read also https://jira.iais.fraunhofer.de/wiki/display/ORInfo/configuration
