### ISSUE TITLE
Integrate NAO v6

### ISSUE THREAD

**Issue by cvejoski** [OpenRoberta/openroberta-lab#32]
NAO v6 uses the Naoqi v2.8 that is backward compatible with NAO v5 using Naoqi v2.1.4. Therefore we do not have to make changes in the HAL. However, for successful integration we have to modify the following:

- [x] NAO-USB program:
   -  [x] Set the environment variables while running the user's created program
   -  [x] Modify the update process of the HAL (separate the HAL for NAO v5 and v6)
- [x] Modify the NAO Client:
    - [x] Remove the _monkey patch_ for the NAO v6,
    - [x] Modify the update process of the HAL (separate the HAL for NAO v5 and v6)
-  [x] Modify the server to accepts different versions of _naoqi_ for the update process of the HAL

**Comment by VinArt** [comment]
We would need to split the NAO client [this one](https://github.com/OpenRoberta/robertalab-naoclient) into two, one for V5 with all needed libraries and the other one for V6 that would be small and build a release for two different versions, because in the app store it is possible to download the app for specific NAO version and it would be nice to make the app not contain unneeded files. We can have two branches for two versions.
