### ISSUE TITLE
Adding the "Say" block first causes a "server error"

### ISSUE THREAD

**Issue by ensonic** [OpenRoberta/openroberta-lab#327]
**Describe the bug**
 - A clear and concise description of what the bug is.

**To Reproduce**
1. Select ev3/ev3dev
2. Add a `Say` block
3. Click on `<>` to see the code
4. A popup "Attention Server-Error" appears

If I add a different block first (e.g. Drive forward), it works.

**Expected behavior**
 - A clear and concise description of what you expected to happen.

**Screenshots**
causes "server error"
![image](https://user-images.githubusercontent.com/1279486/69432537-2ea43880-0d3a-11ea-8159-df0f38540abd.png)
works:
![image](https://user-images.githubusercontent.com/1279486/69432490-18967800-0d3a-11ea-80cc-193362bdf33a.png)

**Device information**
 - Type Desktop
 - OS: debian linux
 - Browser: chrome 78.0

**Comment by boonto** [comment]
After some investigation this happens because I removed the `isSayTextUsed()` and replaced that by adding a dummy `VOICE` actor to the used actors when the say block is used. Then, when creating the used actor map no corresponding configuration component exists.

I think the real solution would be to add an internal configuration component for the voice capability, however this would only be easy for the new configuration.

For now there are two workarounds:
- go back to `isSayTextUsed()`
- check for the `VOICE` actor during map creation

I think the second option is best for now as it can be removed once we switch to the new configuration.

**Comment by VinArt** [comment]
Works with say block as first block, though it might need a corresponding config block in future (e.g. language setting)
