### ISSUE TITLE
EV3: Setting volume to 0 does not decrease the volume

### ISSUE THREAD

**Issue by Blippy2019** [OpenRoberta/openroberta-lab#439]
**Describe the bug**
 - Setting the volume to 0 % does not do anything to the EV3 sound, it sounds the same as when the volume is 100 %

**To Reproduce**
1. Find the "set volume %" block
2. Set input to 0 %
3. Play any sound

**Expected behavior**
 - There should be no sound output as the volume is set to 0%

**Screenshots**
 - 
![image](https://user-images.githubusercontent.com/58810680/71552361-a8bd9080-2a4f-11ea-87fc-76f308d5ccc1.png)
![image](https://user-images.githubusercontent.com/58810680/71552370-d86c9880-2a4f-11ea-8f89-7166ed8d904e.png)

**Device information**
 - Type: Desktop
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
 - Simulation only!
 - According to the help information, 0% would be no sound at all.

**Comment by boonto** [comment]
Needs testing whether this is the case for the real robot as well.

**Comment by boonto** [comment]
Volume does not work because `GainNode` is not used, instead the oscillator is connected directly (See [this](https://stackoverflow.com/questions/43386277/how-to-control-the-sound-volume-of-audio-buffer-audiocontext) and [this](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API)).
Additionally, a volume of `0` is not evaluated correctly in an if, fixed when merging #518.
