### ISSUE TITLE
Can not open simulation, if the "to (var) append text (string)" block is used

### ISSUE THREAD

**Issue by philippmaurer** [OpenRoberta/openroberta-lab#45]
**Describe the bug**
It is not possible to open or start the simulation, if the "to (var) append text (string)" block is used in the program. The simulation either wont open, or it will not start, if it was opened before the block was part of the program.
![Screenshot-2019-5-22 Open Roberta Lab(2)](https://user-images.githubusercontent.com/10925094/58461485-1ad39d00-8130-11e9-86de-f9eaf3350541.png)

**To Reproduce**
1. Choose one of the following robot systems: NXT, EV3, micro:bit, calliope (any with a simulation)
2. Open or create a program, that uses the "to (var) append text (string)" block. You can fill the parameters of the block with any legal or illegal combination of strings and variables.
3. Open the simulation. It will not work.

**Expected behavior**
The block should work as intended in the simulation. It does work on the robot, though.

**Screenshot**
![Screenshot-2019-5-28 Open Roberta Lab](https://user-images.githubusercontent.com/10925094/58461926-122f9680-8131-11e9-8de6-1bc000147929.png)

**Device information**
- Environment: Test and production
- Tested if the block works on the robot: NXT (works)

**Comment by rbudde** [comment]
Works now on both Calliope and simulator. I consider the code generation for the Calliope as a temporara solution, because NO check is done, whether the left hand parameter is a variable (must be). If it is a literal, the following problematic code is generated:

`ManagedString("a") = ManagedString("a") + ManagedString(ManagedString("a"));`

The check visitor should detect this and emit an error

**Comment by rbudde** [comment]
Issue should be moved to the next relaese project
