### ISSUE TITLE
EV3(lejos): missing cast from double to float for pow(double a, double b) function

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#536]
**Describe the bug**
see screenshot

**Expected behavior**
all programs using the pow function should be compilable

**Screenshots**
 - If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/1613069/72285788-28e51800-3644-11ea-8a35-36076e2f315c.png)

**Additional context**
Please check if other math functions are affected too.

**Comment by boonto** [comment]
I added casts to the affected math functions.

This happened due to the removal of RobertaFunctions which had these methods wrapped with float casting. It didn't pop up in any tests (not even the ones currently in development in #364; will be adapted accordingly) because those functions are probably used in "show Text" blocks which have implicit casting through `String.valueOf()`.
