### ISSUE TITLE
Multiple robot simulation: Dropdown menu for selecting robots in sensor view does not display the options

### ISSUE THREAD

**Issue by Caffetaria** [OpenRoberta/openroberta-lab#541]
**Describe the bug**
 - When using the multiple robot simulation, the dropdown menu in the sensor's data view does not display the different robot options. Instead a blank dropdown menu is displayed. The colour of the robot is shown only when an option from the dropdown menu is selected.

**To Reproduce**
1. Create 2 or more nepo programs and use them in multiple robot simulation.
2. Go to the sensor's data view.
3. Click on the dropdown menu to change the robot.

**Expected behavior**
 - The dropdown menu should display the different robot options.

**Screenshots**
 - 
<img width="642" alt="Screen Shot 2020-01-14 at 3 25 32 PM" src="https://user-images.githubusercontent.com/9400738/72346499-1d552800-36fc-11ea-81a5-d9216351115f.png">

**Device information**
 - Type: Desktop
 - OS: MacOS
 - Browser: Chrome

**Comment by KevinL10** [comment]
This issue is reproducable only under certain conditions:
**Windows**

-Chrome: cannot be produced

-Firefox: cannot be produced

-Internet Explorer: cannot be produced

**MacOs**
-Chrome: reproducable

-Firefox: cannot be produced

-Safari: cannot be produced

**Ubuntu**

-Firefox: reproducable 

The html is generated here:
![robotIndex](https://user-images.githubusercontent.com/58920989/72666598-dd769500-39c8-11ea-9e0a-64df3f3b91b6.PNG)

**Comment by bjost2s** [comment]
fixed with #907
