### ISSUE TITLE
New configuration seems to change positions of the board's svg

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#933]
here is the standartconfiguration of calliope before storing
![image](https://user-images.githubusercontent.com/1613069/101683345-1dbd8680-3a65-11eb-80f3-ccc1553a15c0.png)
which is ok 
and here how it looks after storing and loading again
![image](https://user-images.githubusercontent.com/1613069/101683474-4180cc80-3a65-11eb-991b-af7af80dfbd0.png)

**Comment by aykborstelmann** [comment]
I found more problems with this way of the configuration svg block:

e.g. 
![grafik](https://user-images.githubusercontent.com/31162687/102090812-38ee1480-3e1e-11eb-8ac3-7e879c97070b.png)

which is not that big of a problem, since it isn't saved anyway.

Or 

![grafik](https://user-images.githubusercontent.com/31162687/102090920-5de28780-3e1e-11eb-9bd0-9608b2f7d6aa.png)

which is a big problem, since it causes a server error.

**Comment by aykborstelmann** [comment]
The problem should be solved. For testing purposes I have created some examples (exported and stored in the db).
[issue-933-testing.zip](https://github.com/OpenRoberta/openroberta-lab/files/5753942/issue-933-testing.zip)

In the DB is one user, username `Ayk` and password `AykAyk` who has programs for Calliope, Microbit and Arduino.
